# See http://readme.drone.io/0.5/usage/overview
pipeline:
  clone:
    depth: 50
    recursive: false
  build:
    image: docker.kbt.io/postgis/build-test:trisquel
    commands:
      - service postgresql start
      - su -l postgres -c "createuser -s `whoami`"
      - ./autogen.sh
      - ./configure
      - make
      - make check
