# See http://readme.drone.io/0.5/usage/overview
pipeline:
  clone:
    image: git
    depth: 50
    recursive: false
  build:
    image: docker.kbt.io/postgis/build-test:trisquel
    commands:
      - ./autogen.sh
      - ./configure
      - make
  check:
    image: docker.kbt.io/postgis/build-test:trisquel
    commands:
      - service postgresql start
      - make check
