# See http://readme.drone.io/0.5/usage/overview
pipeline:
  clone:
    image: git
    depth: 50
    recursive: false
  build:
    # See https://git.osgeo.org/gogs/postgis/postgis-docker
    image: docker.kbt.io/postgis/build-test:trisquel
    commands:
      - ./autogen.sh
      - ./configure CFLAGS="-O0 -Wall"
      - make
  check:
    image: docker.kbt.io/postgis/build-test:trisquel
    commands:
      - service postgresql start
      - make check
