# See http://readme.drone.io/usage/overview
pipeline:
  build:
    image: docker.kbt.io/postgis/build-test:trisquel
    commands:
      - service postgresql start
      - ./autogen.sh
      - ./configure
      - make
      - make check
