name: MSYS2
on: [push, pull_request]

jobs:
  mingw:
    name: mingw
    runs-on: windows-latest
    strategy:
      matrix:
        #fail-fast: false
        include:
          - { icon: '⬛', sys: mingw32 }
          - { icon: '🟦', sys: mingw64 }
          - { icon: '🟨', sys: ucrt64  } # Experimental!
          - { icon: '🟧', sys: clang64 } # Experimental!
    defaults:
      run:
        shell: msys2 {0}
    steps:
      # see https://github.com/msys2/setup-msys2
    - name: checkout
      uses: actions/checkout@v2
    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          git
          make
          bison
        pacboy: >-
          toolchain:p
          autotools:p
          geos:p
          proj:p
          gdal:p
          sfcgal:p
          json-c:p
          gettext:p
          libxml2:p
          postgresql:p

    - name: '🚧 Build TOOL'
      run: |
        MSYSTEM= ./autogen.sh
        MSYSTEM= ./configure --with-pgconfig=/${{ matrix.sys }}/bin/pg_config --without-protobuf
        MSYSTEM= make

